server:
  port: 9001
  context-path: /resource
  
security:
  sessions: NEVER

spring:
  datasource:
    url: jdbc:mysql://192.168.18.10:3306/mobile_dev
    username: root
    password: Sample@2018
    
app:
  oauth2:
    sigingkey: lvds@2018